ALTER TABLE filters ADD COLUMN applies_to_bw INTEGER NOT NULL DEFAULT 1;
ALTER TABLE filters ADD COLUMN applies_to_color INTEGER NOT NULL DEFAULT 1;
ALTER TABLE filters ADD COLUMN applies_to_infrared INTEGER NOT NULL DEFAULT 1;
